CC = gcc
FLAGS = -fopenmp



polynomial: 	
			${CC} ${FLAGS} basicDumb.c -o basicDumb;
			${CC} ${FLAGS} basicOptimized.c -o basicOptimized;				
			${CC} ${FLAGS} estrin.c -o estrin;
			${CC} ${FLAGS} horner.c -o horner;
			${CC} ${FLAGS} parallelHorner.c -o parallelHorner;
			${CC} ${FLAGS} prefixSumV1.c -o prefixSumV1;
			${CC} ${FLAGS} prefixSumV2.c -o prefixSumV2
				

			